application: simple-picasa
version: 1
runtime: php
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fancybox
  static_dir: fancybox

- url: /album
  script: album.html

- url: /fbpage
  script: fbpage.html

- url: /.*
  script: index.html

